### ISSUE TITLE
build ROM

### ISSUE THREAD

**Issue by zhouxinghui** [ubports-dipper/xiaomi-dipper#2]
How to build a compilation environment for Ubuntu

**Comment by istadem2077** [comment]
Hello @zhouxinghui, I didn't get your question. Do you mean environment for building Ubuntu Touch yourself? There is an official documentation from UBports. In case with this particular device, you need gcc/clang, and mkbootimg, build.sh script builds kernel, and another couple scripts build installable Recovery and System images.

**Comment by istadem2077** [comment]
I guess I can close this issue.
