### ISSUE TITLE
Cannot find the neccesary img files

### ISSUE THREAD

**Issue by DSamaryan** [ubports-dipper/xiaomi-dipper#3]
Hey hey @istadem2077 

We noticed that the link to the latest archive in the README leads to 404 github page. We tried to take another archive from 24 release but couldn't find recovery.img and system.img in there that are neccesary to install ubunto according to the Install section in the README

https://github.com/ubports-dipper/xiaomi-dipper/releases/tag/v24

Could you please point me out to some release with zip file where all of these `.img` files are available

Thanks in advance

**Comment by istadem2077** [comment]
> Hey hey @istadem2077
> 
> We noticed that the link to the latest archive in the README leads to 404 github page. We tried to take another archive from 24 release but couldn't find recovery.img and system.img in there that are neccesary to install ubunto according to the Install section in the README
> 
> https://github.com/ubports-dipper/xiaomi-dipper/releases/tag/v24
> 
> Could you please point me out to some release with zip file where all of these `.img` files are available
> 
> Thanks in advance

Hi, .img files mentioned in README no longer exist. You gotta install the zip files through TWRP, and then install boot.img from [here](https://github.com/Akitlove/kernel-xiaomi-sdm845-dipper/releases/tag/halium9.0).

My boot images appear to be broken. I no longer have the phone, so I can't really support it anymore unfortunately.
